### ISSUE TITLE
USV016 En tant que client, je peux créer un compte 

### ISSUE THREAD

**Issue by Machaux** [DTAFormation/ecommerce-frontend-mobile#10]
Création d'un compte client.
A partir d'une page d'un formulaire de création de compte, un client peut enregistrer son compte dans la base de donnée du serveur.
A la création, il faut remplir les champs suivants:
- nom : (max: 40 char, non nul).
- prénom : (max: 40 char, non nul).
- login : (type email, non nul).
- password : (type password, non nul, min : 6 char).
- confirmation password (type password, identique au champ précédent).

si les conditions ne sont pas remplies, les informations ne sont pas transmises au serveur.
Une fois les données envoyées, le client est redirigé vers la page de login avec le message "compte créé avec succès".

**Comment by NathanGUILLOTEAU** [comment]
Mettre les messages d'erreur du formulaire en rouge. 

La modale est un peu gênant. Un toast serait plus pertinent. On peut aussi mettre une espèce de timmer sur la modale.
