### ISSUE TITLE
USV001 - En tant que client, je peux afficher la liste des produits

### ISSUE THREAD

**Issue by LebonJo** [DTAFormation/ecommerce-frontend-mobile#11]
<h1>Objectifs</h1>

<p>
La page doit afficher dans un tableau :
<ul>
   <li>le nom du produit</li>
   <li>une miniature</li>
   <li>le prix</li>
   <li>un bouton pour l'ajouter au panier</li>
  <li>un bouton pour afficher les détails du produit</li>
</ul>
</p>

</p>Cliquer sur l'encart du produit doit rediriger vers sa page de détail.</p>

**Comment by NathanGUILLOTEAU** [comment]
Décoller les boutons "Ajouter au panier" et "Détails du produit". 
Il faudrait avoir accès aux détails d'un produit en cliquant sur son image.
