### ISSUE TITLE
USV002 - En tant que client, je peux voir les détails d'un produit

### ISSUE THREAD

**Issue by PaulieKlein** [DTAFormation/ecommerce-frontend-mobile#14]
La page doit afficher les détails des produits  après que le client est cliqué sur le produit dans la liste:
- le nom du produit
- les caractéristiques
- le prix
- l'image du produit
- un bouton pour l'ajouter au panier
- redirection vers la page d'accueil.

**Comment by NathanGUILLOTEAU** [comment]
[USV0027](https://github.com/DTAFormation/ecommerce-frontend-mobile/issues/23) - Il faudrait pourvoir accéder au détails des produits depuis le panier et depuis la page home.
