### ISSUE TITLE
USV010 - En tant que client, je peux modifier mon panier.

### ISSUE THREAD

**Issue by LebonJo** [DTAFormation/ecommerce-frontend-mobile#15]
<h1>Objectifs</h1>

<ul>
       <li>Pour chaque produit, afficher : <ul><li>son image</li><li>son libéllé</li><li>son prix</li></ul></li>
       <li>Pouvoir modifier la quantité pour chaque produit</li>
       <li>Afficher le montant total du panier</li>
</ul>

**Comment by NathanGUILLOTEAU** [comment]
[USV0028](https://github.com/DTAFormation/ecommerce-frontend-mobile/issues/24) - Pour la quantité de produits dans le panier, il faut passer le minimum à 1, au lieu de 0.
