### ISSUE TITLE
USV015 - En tant que client, je peux effectuer le paiement

### ISSUE THREAD

**Issue by PaulieKlein** [DTAFormation/ecommerce-frontend-mobile#18]
Objectifs, après que le client a fait son choix de paiement:
-si paiement par chèque : l'adresse apparaît
-si paiement par CB : un formulaire apparaît avec type de CB (image),numéro de carte, date de fin de validité, cryptogramme visuelle et la possibilité de valider ou d'annuler le paiement

**Comment by NathanGUILLOTEAU** [comment]
Le bouton "Payer" doit être visible, même quand on n'est pas connecté. Ajouter un message du genre "Pour payer, il faut se connecter". 

Modifier le Deploy pour prendre en compte les fichiers .jpg .png ou autres afin d'avoir les images des cartes visibles lors du paiement. 

Rendre l'adresse d'envoie des chèques dynamique. 

**\* BLOQUANT ***
L'affichage de la modale pour le cryptogramme ne fonctionne pas. 
Le bouton "Valider" ne fait rien. 
-----> SOLUTION : retirer le "/" au début du chemin.

**Comment by ducloux-b** [comment]
Ajouter au flux de données: Adresse de livraison (+ Adresse de facturation), liste de produits

**Comment by dlecan** [comment]
Reste à faire : contrôles de formulaire
