### ISSUE TITLE
USV013 - En tant que client, je peux choisir l'adresse de livraison où sera livrée la commande

### ISSUE THREAD

**Issue by Joux17** [DTAFormation/ecommerce-frontend-mobile#25]
Lorsque l'utilisateur est sur la page de paiement il peut choisir à quelle adresse il veut se faire livrer la commande une fois qu'il aura appuyer sur le bouton `Payer`.
Pour cela il aura accès à un menu qui lui permettra d'afficher ses adresses et de choisir celle désirée.

**Comment by Joux17** [comment]
il y a aussi les tests du login et du isConnected

**Comment by Joux17** [comment]
BUG : Quand on est sur la page de paiement le prix total est affiché. Si on actualise la page le prix total  passe à 0...

**Comment by Joux17** [comment]
2 listes déroulantes pour les adresses de livraison ???

**Comment by dlecan** [comment]
Terminé
