### ISSUE TITLE
USV013T - Extraire une directive d'un produit de l'écran magasin

### ISSUE THREAD

**Issue by Remidendooven** [DTAFormation/ecommerce-frontend-mobile#29]
Faire une directive d'un produit d'écran de magasin. Le produit est défini par une image, un prix, un libelle. On peut, grâce à deux boutons, l'ajouter au panier et voir les détails.

**Comment by ducloux-b** [comment]
Revue:
Cette directive semble fonctionnelle. Il y a bien toutes les informations mentionnées et les boutons fonctionnent de manière, semble-t-il adéquate.

**Comment by dlecan** [comment]
Terminé
