### ISSUE TITLE
USV012T - Extraire une directive d'un produit du panier

### ISSUE THREAD

**Issue by Joux17** [DTAFormation/ecommerce-frontend-mobile#34]
Faire une directive pour les produits du panier. 
Le produit est défini par une image, un prix, un libelle.
On peut, grâce à deux boutons en faire varier la quantité.
Un bouton supprimer est également présent afin de pouvoir supprimer le produit du panier.

**Comment by Joux17** [comment]
issue mise en pause. 
Code disponible dans la branche : https://github.com/DTAFormation/ecommerce-frontend-mobile/tree/feature-usv012T-directive-panier

**Comment by dlecan** [comment]
Terminé
