### ISSUE TITLE
USV019-En tant que client je veux pouvoir consulter les commandes que j'ai passées

### ISSUE THREAD

**Issue by ducloux-b** [DTAFormation/ecommerce-frontend-mobile#38]
Dans la navbar, sous le bouton Compte, le bouton commande doit mener à une page qui affiche la liste des commandes.
On doit pouvoir afficher les informations relatives à chacune des commandes (produits, adresse de livraison,...).
On doit avoir accès aux détails des produits (note : #/detailsProduit/{idCommande}).

**Comment by dlecan** [comment]
Terminé
