### ISSUE TITLE
USV017 - En tant que client, je peux m'authentifier pour accéder à mon compte

### ISSUE THREAD

**Issue by RomainFarau** [DTAFormation/ecommerce-frontend-mobile#9]
Objectifs
-Page avec formulaire qui demande login et mot de passe
-Vérification des informations de connexion
-Stockage des informations de connexion en session

**Comment by NathanGUILLOTEAU** [comment]
Ajouter un titre "Connexion" à la page. 

**\* IMPORTANT ***
Remettre l'id dans le local storage.
